# 
1) Generate an array of zeroes using inbuilt numpy function.

In [3]:
import numpy as np
Zero_array=np.zeros((4,4))
print(Zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2) Run the given code and find the dot product of both arrays.

In [11]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print("Array a : ",a)
print("Array b : ",b)
Dot_product=a.dot(b)
print("Multiplication of a And B array is :",Dot_product)

Array a :  [[6 6 7 3]
 [5 8 7 8]
 [8 6 2 2]]
Array b :  [[8 6 5]
 [5 9 5]
 [7 2 5]
 [9 8 5]]
Multiplication of a And B array is : [[154 128 110]
 [201 180 140]
 [126 122  90]]


3)Read the csv file provided using pandas and display the first 5 entries

In [13]:
import pandas as pd
file=pd.read_csv("/content/data.csv")
file.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

4)Describe the data with all features.

In [14]:
file.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

5)Find the total count of missing values for each feature.

In [29]:
null_values=pd.isnull(file).count()
print("Total Missing values From Each Features\n: ",null_values)

Total Missing values From Each Features
:  OBJECTID       25
UNIT_NAME      25
DESCRIPTION    25
ACRES          25
SHAPE.AREA     25
SHAPE.LEN      25
dtype: int64


6)Display all the unique values from the 'DESCRIPTION’ column.

In [41]:
unique_Values= file.DESCRIPTION.unique()
print("Unique Values in Description Columns:\n",unique_Values)

Unique Values in Description Columns:
 ['State Park' 'Interpretive Center' 'State Recreation Area'
 'State Natural Area' 'State Nature Preserve']


Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [43]:
file.groupby("DESCRIPTION").mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

8)Generate a random sample of 10 rows from the data

In [47]:
random=file.sample(n=10)
random.head()

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
3         24                      Fort Ransom State Park  ...   0.000444   0.128733

[5 rows x 6 columns]

9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [50]:
file['New_features']=np.random.uniform(0,1)
file.New_features

0     0.663589
1     0.663589
2     0.663589
3     0.663589
4     0.663589
5     0.663589
6     0.663589
7     0.663589
8     0.663589
9     0.663589
10    0.663589
11    0.663589
12    0.663589
13    0.663589
14    0.663589
15    0.663589
16    0.663589
17    0.663589
18    0.663589
19    0.663589
20    0.663589
21    0.663589
22    0.663589
23    0.663589
24    0.663589
Name: New_features, dtype: float64

10) Replace zero value of column 'OBJECTID' with mean value permanently

In [54]:
mean=file.OBJECTID.mean()
file.OBJECTID.replace(0,mean)

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64